blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

blogs/urls.py
"""Defines URL patterns for blog posts."""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
# Home page
    path('', views.index, name='index'),
#Page that shows all posts.
    path('posts/', views.posts, name='posts'),
# Detail for a single post.
    path('posts/<int:post_id>/', views.post, name='post'),
# Page for adding a new blog post.
    path('new_post/', views.new_post, name='new_post'),
# Page for adding a new entry under the blog post.
    path('new_entry/<int:post_id>/', views.new_entry, name='new_entry'),
# Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
# Page for showing registration error.
    path('register_error/', views.register_error, name='register_error'),
]

users/urls.py
"""Defines URL patterns for users."""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
# include default auth urls.
    path('', include('django.contrib.auth.urls')),
# Registration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """A blog post the user is writing about."""
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

class Entry(models.Model):
    """Something about the blog post."""
    topic = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost, Entry

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title']
        labels = {'title': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import BlogPost, Entry
from .forms import BlogForm, EntryForm

def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')

def register_error(request):
    """Show an error page."""
    return render(request, 'blogs/register_error.html')

def posts(request):
    """Show all posts."""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)

def post(request, post_id):
    """Show a single post and all its entries."""
    post = BlogPost.objects.get(id=post_id)
    entries = post.entry_set.order_by('-date_added')
    context = {'post': post, 'entries': entries}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    """Add a new blog post."""
    if request.method != 'POST':
    # No data submitted, create a blank form.
        form = BlogForm()
    else:
    # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
        return redirect('blogs:posts')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def new_entry(request, post_id):
    """Add a new entry for a particular blog post."""
    post = BlogPost.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
    # No data submitted; create a blank form.
        form = EntryForm()
    else:
    # Post data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = post
            new_entry.save()
            return redirect('blogs:post', post_id=post_id)

    # Display a blank or invalid form.
    context = {'post': post, 'form': form}
    return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    post = entry.topic
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
    #Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
    # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
        return redirect('blogs:post', post_id=post.id)

    context = {'entry': entry, 'post': post, 'form': form}
    return render(request, 'blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
    # Display blank registration form.
        form = UserCreationForm()
    else:
    # Process completed form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
        # Log the user in and then redirect to home page.
            login(request, new_user)
        else:
            return redirect('blogs:register_error')
        return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<! doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">
  <title>Azaya's Blog</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary p-3 mb-4">
    <a class="navbar-brand" href="{% url 'blogs:index' %}"> Azaya's Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:posts' %}">Posts</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h2>
{% endblock page_header %}

{% block content %}
<h3>Edit entry:</h3>

<form action="{% url 'blogs:edit_entry' entry.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Save changes</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
<div class="jumbotron">
  <h2 class="display-4">Write about your interests.</h2>
  <p class="lead">Have your say. Write about the things you are interested in and let others read your thoughts and opinions.</p>
  <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
  role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h2>
{% endblock page_header %}

{% block content %}
<h3>Add a new entry:</h3>
<form action="{% url 'blogs:new_entry' post.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary">Add entry</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Add a new topic:</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:new_post' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name="submit" class="btn btn-primary p-3">Add topic</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h3>{{ post }}</h3>
{% endblock page_header %}

{% block content %}
<p>
  <a href="{% url 'blogs:new_entry' post.id %}">Add new entry</a>
</p>

{% for entry in entries %}
<div class="card mb-3">
  <h4 class="card-header">
    {{ entry.date_added|date:'M d, Y H:i' }}
    <small><a href="{% url 'blogs:edit_entry' entry.id %}">Edit entry</a>
    </small>
  </h4>
  <div class="card-body">
  {{ entry.text| linebreaks }}
  </div>
</div>
{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h1>Posts</h1>
{% endblock page_header %}

{% block content %}
<ul>
  {% for post in posts %}
  <li><h3>
    <a href="{% url 'blogs:post' post.id %}">{{ post }}</a> - by {{ post.owner }}
  </h3></li>
  {% empty %}
  <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}
</ul>

<h4><a href="{% url 'blogs:new_post' %}">Add a new topic</a></h4>

{% endblock content %}

blogs/templates/blogs/register_error.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h2>Registration failed. Pls try again.</h2>
{% endblock page_header %}